{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "72840460",
   "metadata": {},
   "outputs": [],
   "source": [
    "from tabulate import tabulate\n",
    "\n",
    "#membuat class Transaction\n",
    "class Transaction:\n",
    "    def __init__(self):\n",
    "        self.order_items = dict()\n",
    "    \n",
    "    #memasukkan nama, jumlah, dan harga item\n",
    "    \n",
    "    def add_item(self, item_name, item_qty, item_price):\n",
    "        self.order_items.update({item_name: [item_qty, item_price]})\n",
    "    \n",
    "        try:\n",
    "            self.item_qty = int(item_qty)\n",
    "            self.item_price = int(item_price)\n",
    "        except:\n",
    "            print(\"Jumlah dan harga barang yang anda masukkan bukan angka. Mohon masukkan angka.\")\n",
    "            \n",
    "    #menampilkan detail pesanan yang sudah diinput\n",
    "    def show_order(self):\n",
    "        show_order = []\n",
    "        header = [\"No.\", \"Nama Barang\", \"Jumlah\", \"Harga per Satuan\", \"Total Harga\"]\n",
    "        show_order.append(header)\n",
    "    \n",
    "        n = 0\n",
    "    \n",
    "        for key, value in self.order_items.items():\n",
    "            n += 1\n",
    "            table_no = n\n",
    "            item_name = key\n",
    "            item_qty = value[0]\n",
    "            item_price = value[1]\n",
    "            total = item_qty * item_price\n",
    "            item_data = [table_no, item_name, item_qty, item_price, total]\n",
    "            show_order.append(item_data)\n",
    "\n",
    "        print(tabulate(show_order, tablefmt=\"fancy_grid\"))\n",
    "        \n",
    "        #mengubah detail pesanan yang sudah diinput\n",
    "    def update_item_name(self, item_name, item_name_new):\n",
    "        temp = self.order_items[item_name]\n",
    "        self.order_items.pop(item_name)\n",
    "        self.order_items.update({item_name_new:temp})\n",
    "\n",
    "\n",
    "    def update_item_qty(self, item_name, item_qty_new):\n",
    "        self.order_items[item_name][0] = item_qty_new\n",
    "\n",
    "\n",
    "    def update_item_price (self, item_name, item_price_new):\n",
    "        self.order_items[item_name][1] = item_price_new\n",
    "        \n",
    "    #menghapus satu atau beberapa item yang telah diinput\n",
    "    def delete_item(self, item_name):\n",
    "        try:\n",
    "            self.order_items.pop(item_name)\n",
    "            print(f\"Item {item_name} telah dihapus\")\n",
    "            print(\"\")\n",
    "        except KeyError:\n",
    "            print(f\"Item {item_name} tidak ditemukan pada daftar pesanan yang telah diinput\")\n",
    "            \n",
    "    #menghapus semua item yang telah diinput\n",
    "    def reset_transaction(self):\n",
    "        transaction = {}\n",
    "        self.order_items = transaction\n",
    "        print(\"Semua pesanan telah dihapus. Anda belum memiliki daftar pesanan\")\n",
    "        \n",
    "        \n",
    "    #memeriksa pesanan yang telah diinput\n",
    "    def check_order(self):\n",
    "        for key, value in self.order_items.items():\n",
    "            item_name = key\n",
    "            item_qty = value[0]\n",
    "            item_price = value[1]\n",
    "\n",
    "        if type(item_name) == str and type(item_qty) == int and type(item_price) == int:\n",
    "            print(\"Input pesanan sudah benar\")\n",
    "        else:\n",
    "            print(\"Terdapat kesalahan input pesanan. Mohon periksa kembali.\")\n",
    "            \n",
    "            \n",
    "    #menghitung total diskon, total pesanan, dan total pesanan setelah diskon\n",
    "    def total_order(self):\n",
    "        self.total_order = 0\n",
    "        for value in self.order_items.values():\n",
    "            item_qty = value[0]\n",
    "            item_price = value[1]\n",
    "            self.total_order += (item_qty * item_price)\n",
    "        get_discount, discount = self.get_discount(self.total_order)\n",
    "        self.final_order = self.total_order - discount\n",
    "\n",
    "        if get_discount == True:\n",
    "            print(f\"Total belanja anda adalah Rp {self.total_order :,} sehingga anda mendapatkan discount sebesar Rp {discount :,}. \\n Total belanja setelah discount adalah Rp {self.final_order :,}\")\n",
    "        else:\n",
    "            print(f\"Total belanja anda adalah {self.total_order :,}\")\n",
    "\n",
    "    def get_discount(self, total_order):\n",
    "        self.total_order = total_order\n",
    "        if self.total_order <= 200_000:\n",
    "            get_discount = False\n",
    "            discount = 0\n",
    "        else:\n",
    "            get_discount = True\n",
    "            if self.total_order > 500_000:\n",
    "                discount = 0.1 * self.total_order\n",
    "            elif self.total_order > 300_000:\n",
    "                discount = 0.08 * self.total_order\n",
    "            elif self.total_order > 200_000:\n",
    "                discount = 0.05 * self.total_order\n",
    "\n",
    "        return get_discount, discount\n",
    "   \n",
    "\n",
    "            "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5cf713d5",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
